In [1]:
import pandas as pd
import numpy as np


In [2]:
dataset = pd.read_csv('weight-height.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  10000 non-null  object 
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB


In [4]:
y = dataset['Weight']

In [5]:
X = dataset['Height']

In [8]:
from keras.layers import Dense
from keras.models import Sequential

In [9]:
model = Sequential()

In [10]:
model.get_config()

{'layers': [], 'name': 'sequential'}

In [13]:
model.add(
  Dense( 
      units = 1,
      bias_initializer='zeros',
      kernel_initializer = 'zeros',
      activation = "linear",
      input_shape = (1,)

      
    )
)

In [14]:
model.add(
  Dense( 
      units = 1,
      bias_initializer='zeros',
      kernel_initializer = 'zeros',
      activation = "linear",
      input_shape = (1,)

      
    )
)

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile(loss="mean_squared_error", optimizer = "Adam")

In [17]:
model.get_weights()

[array([[0.]], dtype=float32),
 array([0.], dtype=float32),
 array([[0.]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
model.fit(X,y)

313/313 [==============================] - 2s 3ms/step - loss: 27043.6582


In [19]:
model.predict([100])

array([[0.31269687]], dtype=float32)

In [20]:
model.save('first-keras-basic')

INFO:tensorflow:Assets written to: first-keras-basic/assets
