In [1]:
def my_function(x,y,z=2):
    if z>1:
        return z*(x+y)
    else:
        return z/(x+y)

In [2]:
my_function(3,2)

10

In [3]:
def func():
    a = []
    for i in range(5):
        a.append(i)

In [4]:
func()

In [8]:
dict = { 'a': 1,'b':2}

In [10]:
for key in dict:
    print(key)

a
b


In [11]:
def attempt_float(x):
    try:
        return float(x)
    except:
        return x
    

In [15]:
attempt_float('something')

'something'

In [16]:
path = ('C:\ARTH Video Lecture')

In [19]:
import numpy as np

data  = np.random.randn(2, 3)
data

array([[ 1.44481696,  0.70402554,  0.61015178],
       [ 0.09016461,  0.01809418, -0.9182621 ]])

In [20]:
data * 10

array([[14.4481696 ,  7.04025537,  6.10151783],
       [ 0.90164607,  0.18094178, -9.18262105]])

In [21]:
data + data

array([[ 2.88963392,  1.40805107,  1.22030357],
       [ 0.18032921,  0.03618836, -1.83652421]])

In [22]:
data.shape

(2, 3)

In [25]:
data.dtype

dtype('float64')

In [26]:
arr = np.array(data)

In [27]:
data

array([[ 1.44481696,  0.70402554,  0.61015178],
       [ 0.09016461,  0.01809418, -0.9182621 ]])

In [28]:
arr = np.arange(10)

In [29]:
arr[2:5]

array([2, 3, 4])

In [30]:
arr = np.empty((8,4))

In [32]:
for i in range(8):
    arr[i] = i

In [33]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [34]:
arr = np.arange(10)

In [36]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
x = np.random.randn(8)
y = np.random.randn(8)


In [39]:
np.maximum(x,y)

array([ 1.21831217,  1.08198201,  1.03633477,  0.19628478, -0.76158431,
        1.29372929,  0.66140348,  0.63227729])

In [40]:
arr=np.random.randn(100)

In [41]:
(arr>0).sum()

50

In [42]:
arr.sort()

In [43]:
arr

array([-2.41725521, -2.38773283, -1.62966375, -1.41126121, -1.38269192,
       -1.26982289, -1.25647357, -1.25292185, -1.17129816, -1.16594011,
       -1.14545759, -1.13290961, -1.10054462, -1.07756807, -0.98772807,
       -0.96344988, -0.9596766 , -0.86738726, -0.86372007, -0.81563357,
       -0.81002573, -0.76048663, -0.74467694, -0.73096414, -0.72468864,
       -0.72229683, -0.6676805 , -0.66530892, -0.62706828, -0.59794439,
       -0.55509441, -0.53216829, -0.52261663, -0.50570047, -0.50375622,
       -0.43851749, -0.3664432 , -0.36490407, -0.31891262, -0.26535426,
       -0.23511619, -0.2153038 , -0.20577088, -0.17752523, -0.16484835,
       -0.12686162, -0.11097761, -0.10383063, -0.10128486, -0.01561865,
        0.05655595,  0.05870792,  0.06084457,  0.08003737,  0.11379459,
        0.1219685 ,  0.15470112,  0.18148146,  0.18727965,  0.20265816,
        0.20553735,  0.21760722,  0.26796594,  0.27958354,  0.3050079 ,
        0.31938691,  0.34188048,  0.39527612,  0.3957724 ,  0.43

In [45]:
 large_arr = np.random.randn(1000)

In [46]:
large_arr.sort()

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [48]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [49]:
arr = np.arange(100)

In [50]:
np.save('some_array',arr)

In [53]:
np.load('some_array.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])