In [1]:
db = ["vimal", "pop", "jack", "eric"]

In [2]:
type(db)

list

In [3]:
db[1:4]

['pop', 'jack', 'eric']

In [4]:
db[1:]

['pop', 'jack', 'eric']

In [5]:
db[:3]

['vimal', 'pop', 'jack']

In [6]:
db[:]

['vimal', 'pop', 'jack', 'eric']

In [7]:
db = [ 
      [ 1,"vimal",1111,"ok"]  , 
       [2,"pop",2222,"good" ], 
        [3,"jack",3333,"ok" ],
       [ 4, "eric", 4444, "good" ] 
     ]

In [8]:
len(db)

4

In [9]:
db[0]

[1, 'vimal', 1111, 'ok']

In [10]:
db

[[1, 'vimal', 1111, 'ok'],
 [2, 'pop', 2222, 'good'],
 [3, 'jack', 3333, 'ok'],
 [4, 'eric', 4444, 'good']]

In [11]:
db[1][3]

'good'

In [12]:
db

[[1, 'vimal', 1111, 'ok'],
 [2, 'pop', 2222, 'good'],
 [3, 'jack', 3333, 'ok'],
 [4, 'eric', 4444, 'good']]

In [13]:
db[1:4]

[[2, 'pop', 2222, 'good'], [3, 'jack', 3333, 'ok'], [4, 'eric', 4444, 'good']]

In [14]:
import numpy

In [15]:
a = numpy.array(db)

In [16]:
type(a)

numpy.ndarray

In [17]:
a.shape

(4, 4)

In [18]:
a[: , 1]

array(['vimal', 'pop', 'jack', 'eric'], dtype='<U21')

In [19]:
a[: , 1:3]

array([['vimal', '1111'],
       ['pop', '2222'],
       ['jack', '3333'],
       ['eric', '4444']], dtype='<U21')

In [20]:
a[1:3 , 1:3 ]

array([['pop', '2222'],
       ['jack', '3333']], dtype='<U21')

In [21]:

# pip install opencv-python
import cv2

In [22]:
photo = cv2.imread('manoj.jfif')

In [23]:
type(photo)

numpy.ndarray

In [24]:
photo.shape

(183, 275, 3)

In [25]:
# crop image
b = photo[10:120 , 30:200 ]

In [26]:
cv2.imwrite("my.jpg" , b)

True

In [27]:
cap = cv2.VideoCapture(0)

In [28]:
# click photo
myphoto = cap.read()

In [29]:
len(myphoto)

2

In [30]:
ret = myphoto[0]

In [31]:
ret

False

In [32]:
aphoto = myphoto[1]

In [33]:
aphoto.shape

AttributeError: ignored

In [ ]:
cv2.imwrite("manoj.png" , aphoto)

True

In [36]:
import numpy as np

In [37]:
a1 = np.array([[1,2],[1,5],[1,10]])

In [38]:
a1

array([[ 1,  2],
       [ 1,  5],
       [ 1, 10]])

In [39]:
a1.shape

(3, 2)

In [40]:
b1 = numpy.array([ [3,3], [4,4], [5,5]])

In [ ]:
b1

array([[3, 3],
       [4, 4],
       [5, 5]])

In [41]:
b1.shape

(3, 2)

In [ ]:
a1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b1

array([[3, 3],
       [4, 4],
       [5, 5]])

In [42]:
c1 = numpy.vstack( (a1, b1)  )

In [43]:
c1.shape

(6, 2)

In [44]:
d1 = numpy.hstack( (a1 , b1))

In [45]:
d1.shape

(3, 4)

In [46]:
d1

array([[ 1,  2,  3,  3],
       [ 1,  5,  4,  4],
       [ 1, 10,  5,  5]])

In [ ]:
a1.shape

(3, 2)

In [48]:
a1.reshape(1,6)

array([[ 1,  2,  1,  5,  1, 10]])

In [47]:
e1 = numpy.array([1,2,3,4,5,6])

In [ ]:
e1.shape

(6,)

In [ ]:
e1

array([1, 2, 3, 4, 5, 6])

In [ ]:
f1 = e1.reshape(-1 , 1)

In [ ]:
f1.shape

(6, 1)

In [49]:
a1.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 1],
       [ 5],
       [ 1],
       [10]])

In [50]:
a1

array([[ 1,  2],
       [ 1,  5],
       [ 1, 10]])