In [1]:
import cv2

In [2]:
cap = cv2.VideoCapture(0)


In [3]:
ret, photo = cap.read()

In [4]:
cap.release()

In [5]:
type(photo)

numpy.ndarray

In [6]:
b,g,r = cv2.split(photo)

In [7]:
b,g,r

(array([[154, 152, 149, ...,  78,  80,  81],
        [157, 154, 151, ...,  80,  82,  83],
        [156, 153, 151, ...,  82,  85,  86],
        ...,
        [ 36,  37,  40, ..., 117, 110, 105],
        [ 29,  31,  35, ..., 117, 113, 109],
        [ 27,  29,  34, ..., 117, 116, 114]], dtype=uint8),
 array([[124, 121, 119, ...,  63,  65,  66],
        [128, 125, 121, ...,  65,  67,  68],
        [130, 127, 124, ...,  67,  69,  70],
        ...,
        [ 42,  42,  43, ..., 117, 110, 105],
        [ 38,  38,  38, ..., 117, 113, 109],
        [ 37,  37,  38, ..., 117, 116, 114]], dtype=uint8),
 array([[106, 105, 105, ..., 102, 103, 104],
        [111, 108, 109, ..., 103, 105, 106],
        [116, 114, 114, ..., 104, 106, 107],
        ...,
        [ 47,  47,  47, ..., 117, 110, 105],
        [ 45,  45,  45, ..., 117, 113, 109],
        [ 47,  46,  47, ..., 117, 116, 114]], dtype=uint8))

In [8]:
photo.shape

(480, 640, 3)

In [ ]:
cv2.imshow("hi", photo)
# cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
nphoto = cv2.blur(photo , (15,15) )

In [8]:
nphoto

array([[[152, 131, 124],
        [152, 131, 124],
        [152, 131, 124],
        ...,
        [ 88,  76, 106],
        [ 88,  76, 106],
        [ 88,  76, 107]],

       [[151, 131, 124],
        [152, 131, 124],
        [152, 131, 124],
        ...,
        [ 88,  76, 106],
        [ 88,  76, 107],
        [ 88,  76, 107]],

       [[151, 131, 124],
        [151, 131, 124],
        [151, 131, 124],
        ...,
        [ 89,  77, 107],
        [ 89,  77, 108],
        [ 89,  77, 108]],

       ...,

       [[ 45,  39,  50],
        [ 45,  39,  51],
        [ 46,  40,  51],
        ...,
        [120, 120, 121],
        [120, 120, 121],
        [120, 120, 121]],

       [[ 45,  39,  50],
        [ 45,  40,  51],
        [ 46,  40,  51],
        ...,
        [120, 120, 120],
        [120, 120, 120],
        [120, 120, 120]],

       [[ 45,  39,  50],
        [ 45,  39,  50],
        [ 46,  40,  51],
        ...,
        [121, 121, 121],
        [121, 121, 121],
        [121, 121, 121]]

In [9]:
cv2.imshow("hi", photo)

In [10]:
cv2.destroyAllWindows()

# live image crop

In [11]:
import cv2

In [12]:
cap = cv2.VideoCapture(0)

In [13]:
ret, photo = cap.read()

In [14]:
cap.release()

In [15]:
ret

True

In [16]:
model = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [17]:
model

<CascadeClassifier 000001196C3F92D0>

In [19]:
type(model)

cv2.CascadeClassifier

In [ ]:
while False:
    ret, photo = cap.read()
    fdetect  = model.detectMultiScale(photo)
    if len(fdetect) == 0:
        print("no faces")
    else:
        x1 = fdetect[0][0]
        y1 = fdetect[0][1]
        x2 = fdetect[0][2] + x1
        y2 = fdetect[0][3] + y1 
        # rphoto = cv2.rectangle(photo , (x1,y1), (x2,y2), [0, 255,0] , 2)
        #cphoto = photo[y1:y2 , x1:x2]
        # bphoto = cv2.blur(cphoto, (15,15))
        cv2.imshow('hi', photo)
        if cv2.waitKey(100) == 13:
            break
        
        
cv2.destroyAllWindows()

In [ ]:
fdetect

In [ ]:
x1 = fdetect[0][0]
y1 = fdetect[0][1]
x2 = fdetect[0][2] + x1
y2 = fdetect[0][3] + y1 

In [ ]:
rphoto = cv2.rectangle(photo , (x1,y1), (x2,y2), [0, 255,0] , 2)

In [ ]:
cv2.imshow('hi', rphoto)
cv2.waitKey()
cv2.destroyAllWindows()